### PR TITLE
Template updates in preparation for course updates

### PR DESCRIPTION
**Pull request by heiskr**
Updates course template in preparation for updates across courses.

### CODE REVIEW

**Review by gracepark — APPROVED** [review]
👍

**Comment by sinsukehlab** [comment]
It looks great, but I wonder how the **Start course** button will work in the courses. It is TBD in this repository.

**Comment by sinsukehlab** [comment]
I don't think a generated repository should have the same name as the template repository. The name should be left for the forked repository.

**Comment by sinsukehlab** [comment]
> It looks great, but I wonder how the **Start course** button will work in the courses. It is TBD in this repository.

Using absolute URI references, that makes sense.

**Pull request merged**
