### PR TITLE
Add `get_current_step` jobs

### PR DESCRIPTION
**Pull request by sinsukehlab**
### Why:

Some courses use `get_current_step` jobs. This feature helps the Actions workflows to function in numerical order.

### What's being changed:

YAML files
Add `get_current_step` jobs

### Check off the following:

- [x] For workflow changes, I have verified the Actions workflows function as expected.
- [ ] For content changes, I have reviewed the [style guide](https://github.com/github/docs/blob/main/contributing/content-style-guide.md).

### CODE REVIEW

**Comment by sinsukehlab** [comment]
I will add some commits to stop using set-output commands.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by sinsukehlab** [comment]
https://docs.github.com/en/actions/learn-github-actions/contexts#needs-context

**Comment by sinsukehlab** [comment]
I have mistakenly reverted the three commits. I am resetting....

**Comment by sinsukehlab** [comment]
At first I reverted those commits, but on second thought I reset the reverting commits, checkouted to 4eecba3, committed the changes and force-pushed the local branch.

Reverting commits that were reset:
647462c
f3b7487
82a7942

**Review by heiskr — APPROVED** [review]
Perfect, thank you :)

We squash commits so I wouldn't put too much effort into the commit history of branches.

**Pull request merged**
